apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limit-range
  namespace: covert-oms
spec:
  limits:
  - defaultRequest:
      ephemeral-storage: "10Mi"
    type: Container
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: branch-agent
  namespace: covert-oms
---

apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: covert-oms
spec:
  limits:
    - type: Container
      defaultRequest:
        memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: branch-agent
  namespace: covert-oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: branch-agent
  template:
    metadata:
      labels:
        app: branch-agent
    spec:
      containers:
        - name: branch-agent
          image: covert-oms-branch-agent:latest
          resources:
            limits:
              memory: 100Mi
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PrintCoordinatorUrl
              value: "http://print-coordinator:8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: branch-agent
  namespace: covert-oms
spec:
  selector:
    app: branch-agent
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
  type: NodePort
