apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: covert-oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: covert-oms-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: covert-oms
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
