apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-coordinator
  namespace: covert-oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print-coordinator
  template:
    metadata:
      labels:
        app: print-coordinator
    spec:
      containers:
        - name: print-coordinator
          image: covert-oms-print-coordinator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: BranchAgentUrl
              value: "http://branch-agent:8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: print-coordinator
  namespace: covert-oms
spec:
  selector:
    app: print-coordinator
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
  type: NodePort
